spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# spring.datasource.initialization-mode=embedded
spring.sql.init.mode=embedded
spring.h2.console.settings.web-allow-others=true
server.port=8080
server.address=0.0.0.0

spring.main.web-application-type=servlet
spring.lifecycle.timeout-per-shutdown-phase=30s

